### ISSUE TITLE
Icon's color

### ISSUE THREAD

**Issue by jrcacd** [HITGIF/TextFieldBoxes#11]
- How to set the icon's color?
- Is there a way to set the icon's color as the primaryColor?

**Comment by Rainer-Lang** [comment]
Maybe possible to set as default with the app theme primary color. And additional to overwrite with an extra method?

**Comment by jrcacd** [comment]
Great!

**Comment by HITGIF** [comment]
So you want the icon to have a different color from the floating label and the bottomLine?
Well, neither me nor the guideline would suggest people to do so, since the icon signifier should act as an indicator that needs to change its color at different situation accordingly to emphasize the state, just like the bottomLine.
So is there really a need to do so?

**Comment by jrcacd** [comment]
Some of the icons I set do not have the color of the floating label and the bottomLine.
So, wath is needed is an option to set the color as such.

**Comment by HITGIF** [comment]
The icon you set are originally with colors or just grayscale? Could you show me some examples of them?

**Comment by jrcacd** [comment]
![image](https://user-images.githubusercontent.com/26005662/30266169-744e7562-96d6-11e7-8870-0a4979d177e6.png)

**Comment by HITGIF** [comment]
You sure it's not changing the color? What's the format of the icon? Or can you give me the image resource that's not working properly since I can't reproduce that with the images I have. Thank you :)

**Comment by jrcacd** [comment]
Sorry, you are right. It is changing the color. 
The activity starts with the controls enabled = false, then, when the form is activated only the control with focus has colored the icon. 
But this results in all the others controls icon to be in gray, diferent from the rest of the forms primary color.

**Comment by HITGIF** [comment]
So the coloring is working properly? It is supposed to be in gray when not having focus, as the label and the bottomLine do.

**Comment by jrcacd** [comment]
Yes it is.
It be great if it was possible that the icon, diferent from the label and the bottom line, remained in the primary color (as an option)

**Comment by HITGIF** [comment]
You can now use `setIsResponsiveIconColor(boolean isrResponsiveIconColor)` in **release 1.2.1** to set whether the icon will change its color when gaining or losing focus as the label and the bottomLine do. Check out README for more detail.

**Comment by jrcacd** [comment]
Ok, thanks
