### ISSUE TITLE
Label very close to text

### ISSUE THREAD

**Issue by jrcacd** [HITGIF/TextFieldBoxes#13]
![image](https://user-images.githubusercontent.com/26005662/30264785-ef1412fc-96d1-11e7-9b2d-3c225ebe61a6.png)

**Comment by HITGIF** [comment]
Interesting... the label should be on the top when there is an input. When did you have this bug? Or how can I reproduce it

**Comment by jrcacd** [comment]
TextFieldBoxes version 1.1.0 and 1.2.0
The field is readonly and I set the text programmatically. It already had the labelText

**Comment by HITGIF** [comment]
That make sense, I'm fixing it. Thx for reporting :)

**Comment by HITGIF** [comment]
**fixed in release 1.2.1**

**Comment by jrcacd** [comment]
Very good
