### ISSUE TITLE
Is there an option for readonly?

### ISSUE THREAD

**Issue by jrcacd** [HITGIF/TextFieldBoxes#15]
Is there an option for readonly? 
So that the field is enabled (with color), but the user cannor write on the field

**Comment by HITGIF** [comment]
Just use `getEditText(). setEnabled()` to disable the EditText only.

**Comment by jrcacd** [comment]
Ok

**Comment by darkyelox** [comment]
There is no a getEditText() method in the TextFieldBoxes class and the TextFieldBoxes must read enabled from the ExtendedEditText xml

**Comment by HITGIF** [comment]
@darkyelox yep, things have been updated from version 1.3.0.
