### ISSUE TITLE
When the field has an error, and I delete all the text, is looses focus

### ISSUE THREAD

**Issue by jrcacd** [HITGIF/TextFieldBoxes#16]

**Comment by HITGIF** [comment]
you set the text to "" using `setText()`? Or noemally deleting with backspace?

**Comment by jrcacd** [comment]
With backspace?

**Comment by HITGIF** [comment]
You deleted the text with code or using keyboard?

**Comment by jrcacd** [comment]
Sorry, by mistake I entered one '?' in my last answer.

I delete the text using keyboard, pressing the backspace key.

**Comment by HITGIF** [comment]
I can't reproduce the error...
I input something, then use `setError()` in java, and delete all the text with backspace, and it acts normal, not losing focus.
![image](https://user-images.githubusercontent.com/16971971/30509074-8990f94c-9a6c-11e7-9c0d-c6c8dd2c32a2.png)

Could you describe how you got the bug in more detail?
