### ISSUE TITLE
how to change backgroud color?

### ISSUE THREAD

**Issue by FynnJason** [HITGIF/TextFieldBoxes#2]

**Comment by HITGIF** [comment]
In the new release 1.0.1 you can use `app:panelBackgroundColor` in xml or `setPanelBackgroundColor(int _colorRes)` in Java to set the color of the panel at the back. It's 6% black (`#06000000`) by default.

*Note that the default color, as in the guideline, is the black (`#000000`) color with the transparency of 6%, so when you're customizing and want it to still be transparent you have to set a color with transparency.*
