### ISSUE TITLE
Unable to import library

### ISSUE THREAD

**Issue by coutlooters** [HITGIF/TextFieldBoxes#24]
How can anyone help me?
@HITGIF 

    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:support-v4:26.+'

   compileSdkVersion 26
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "***"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:design:26.0.1] AndroidManifest.xml:28:13-35
	is also present at [com.android.support:appcompat-v7:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**Comment by HITGIF** [comment]
Try to use `buildToolsVersion "26.1.0` instead of
`buildToolsVersion "26.0.0'`
