### ISSUE TITLE
Change size of the Label text

### ISSUE THREAD

**Issue by manuellq** [HITGIF/TextFieldBoxes#26]
Sometimes the size of the label text is too big and take two lines so when the edit text has the focus it animate to the top it still taking two lines but now there are enough space to fill it in one line

**Comment by HITGIF** [comment]
You can use `getFloatingLabel()` then customize it.

**Comment by HITGIF** [comment]
But why it's too big..?
Can you provide screenshot?

**Comment by manuellq** [comment]
Hi.

![device-2017-10-15-093843](https://user-images.githubusercontent.com/6086383/31583225-bbbd2916-b18e-11e7-855d-c556bedfa11e.png)
![device-2017-10-15-093435](https://user-images.githubusercontent.com/6086383/31583228-cb1c43ce-b18e-11e7-9f94-f7290e24c01e.png)

**Comment by HITGIF** [comment]
Well... this much information is improper to be put in the label as it would drastically worsen the user experience... You should try to use a hint instead.

Yet if you insist to do so, you can use `getFloatingLabel().setMaxLines(1)` to force it to stay in a line :)

**Comment by manuellq** [comment]
I'm complete agree with you but is there any chance to change the size of the label when the Edit text has not the focus.

**Comment by HITGIF** [comment]
Did customizing ` getFloatingLabel()` work?
