### ISSUE TITLE
Change color of underline when TextField is out of focus

### ISSUE THREAD

**Issue by Kundaemon** [HITGIF/TextFieldBoxes#27]
I didn't find the way how to change default black color of underline when TextField is not focused.
Background or Foreground tint doesn't help.

**Comment by HITGIF** [comment]
Currently you can't change it because it is set to be `android.R.attr.textColorTertiary` of the current theme.

**Comment by pess0a** [comment]
There is no way to change it?...

**Comment by HITGIF** [comment]
@pess0a Currently nope... Yet I'm working on making it customizable with issue #28 
I'll let you know when you're able to do that :)

**Comment by HITGIF** [comment]
You can now do that in 1.3.5 release with `app:secondaryColor` attribute :)
