### ISSUE TITLE
Change color of Label when not in focus

### ISSUE THREAD

**Issue by mournblade** [HITGIF/TextFieldBoxes#28]
Great library, thanks. One issue - the "app:labelText"  has the right color when the field is tapped and the text moves up into the upper left corner. When out of focus, though, it is white and none of the settings you have seem to make any difference. Would be great if it were possible to change that color as well.

**Comment by HITGIF** [comment]
I'll make it customizable soon :)
Now its using the `TertiaryTextColor` of the current theme.

**Comment by HITGIF** [comment]
You can now do that in 1.3.5 release with `app:secondaryColor` attribute :)

**Comment by mournblade** [comment]
Hey, a bit late on the ball, but thanks a lot :) (you know how it is with work....)
