### ISSUE TITLE
setError() doesn't work on Android 5.1.1

### ISSUE THREAD

**Issue by ako2345** [HITGIF/TextFieldBoxes#30]
`setError(String errorText, boolean giveFocus)` doesn't display an error message on Nexus 5 (Android 5.1.1). Version: 1.3.4.

**Comment by HITGIF** [comment]
What do you mean by "doesn't display an error message"?
Did it turn red?
Is there anything on the bottom left corner?
Providing a screenshot and the code for calling that method would be helpful :)

**Comment by ako2345** [comment]
I checked everything one more time and it's OK now. I guess the issue should be closed. Thanks for the library!
