### ISSUE TITLE
Move label up after calling setText()

### ISSUE THREAD

**Issue by ako2345** [HITGIF/TextFieldBoxes#31]
After calling `ExtendedEditText#setText(String s)` TextFieldBoxes displays only its label, the text is not visible. I expect the following behavior: after setting a text the label moves to the top of TextFieldBoxes view and the text is shown in EditText.

**Comment by ako2345** [comment]
The problem can be solved by calling `TextFieldBoxes#activate(false)`. Can you make it public?

**Comment by HITGIF** [comment]
This is a bug, and that method should be called when the text changes. I've fixed it and it will cone out in the next release :)

**Comment by HITGIF** [comment]
fixed in 1.3.5 release :)
