### ISSUE TITLE
compile 'com.github.HITGIF:TextFieldBoxes:1.3.6' doesnt work.

### ISSUE THREAD

**Issue by pess0a** [HITGIF/TextFieldBoxes#36]
Failed to resolve: com.github.HITGIF:TextFieldBoxes:1.3.6

Version 1.3.5 still working. 
1.3.6 has some erros on build.

![image](https://user-images.githubusercontent.com/5043230/32904582-6cff05cc-cad6-11e7-98e0-2ac45d99be5a.png)

**Comment by HITGIF** [comment]
now fixed :)
Sorry for that
