### ISSUE TITLE
Label is not centered vertically when height of TextFieldBoxes is custom

### ISSUE THREAD

**Issue by ako2345** [HITGIF/TextFieldBoxes#39]
I set the height of TextFieldBoxes to 80dp and label in inactive state wasn't in the center of the container.

**Comment by HITGIF** [comment]
It doesn't have to be...
The label will remain at the top left when height increases as in the guideline.

**Comment by ako2345** [comment]
You are talking about an active state, but my problem occurs when text is empty, a view has no focus and TextFieldBoxes contains only label text.

**Comment by HITGIF** [comment]
Well, its position is fixed. If the 80dp is without helper or counter text (bottom space hidden), then its height is greater than `wrap_content` and it should behave something like the second one in the picture below:
![tfb](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B5ZSepuCX1xOZE9xMzJTRVM2djA/discoverable-area1.png)

If it's the case which the 80dp includes the bottom helper space, then the height is smaller than `wrap_content`, and the label is slightly below the center, which is probably what you've encountered. However, as I mentioned in #40, shrinking the height is not suggested and will cause other issues, so shrinking is not a good idea in the first place.
