### ISSUE TITLE
Use another text widget, for example AutoCompleteTextView

### ISSUE THREAD

**Issue by BenoitDuffez** [HITGIF/TextFieldBoxes#43]
Thanks for your lib, it's really great to have it.

I would like to know how I could use it for autocomplete text views? I tried to wrap one inside a `TextFieldBoxes` but this fails:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
    at studio.carbonylgroup.textfieldboxes.TextFieldBoxes.setLabelText(TextFieldBoxes.java:748)
    at studio.carbonylgroup.textfieldboxes.TextFieldBoxes.triggerSetters(TextFieldBoxes.java:718)
    at studio.carbonylgroup.textfieldboxes.TextFieldBoxes.onFinishInflate(TextFieldBoxes.java:224)
```

I'm guessing I can't put any widget I want there. Is there a way I could hack this in?
Thanks

**Comment by HITGIF** [comment]
Thank you.
Can you provide your xml layout please?

**Comment by BenoitDuffez** [comment]
<studio.carbonylgroup.textfieldboxes.TextFieldBoxes
        android:id="@+id/tfb"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/catch_species_value"
        app:labelText="Weight">

        <AutoCompleteTextView
            android:id="@+id/value"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    </studio.carbonylgroup.textfieldboxes.TextFieldBoxes>

**Comment by HITGIF** [comment]
Fixed in **Release 1.3.8** :)

**Comment by BenoitDuffez** [comment]
Oh great thanks!

Do you think it would be possible to use custom views of some kind? Like if I want to use widget X, I would have to subclass it and add methods M, N, and O so that it's compatible with a `TextFieldBoxes`?

Right now I'm thinking about a spinner, I know it's not in the spec but I'm curious how it would look. I don't want to make you implement everything in the lib so I'm asking if it's feasible to do it on my own.

**Comment by BenoitDuffez** [comment]
I think this is too much of a bad idea for UI and material design compliance. Ignore that. :)

**Comment by dineshmm23** [comment]
Please add `auto Complete` Feature in `table contents`
