### ISSUE TITLE
Feedback TextFieldBoxes problem

### ISSUE THREAD

**Issue by TCQQ** [HITGIF/TextFieldBoxes#44]
Hi, thank you your library, how to customize the font?

**Comment by HITGIF** [comment]
Sorry for the late reply :)

You can use `android:fontFamily` in xml to set the font of the `ExtendedEditText`.
Alternatively, you can use `setTypeface()` in java code, which can also, via getters, be used to customize the font of the label, counter, helper etc.

For example, to make the helper text italic:
```java
final TextFieldBoxes tfb = findViewById(R.id.text_field_boxes);
tfb.getHelperLabel().setTypeface(null, Typeface.ITALIC);
```

Refer [here](https://developer.android.com/reference/android/widget/TextView.html#setTypeface(android.graphics.Typeface)) for more details :)

**Comment by TCQQ** [comment]
Thankyou.
