### ISSUE TITLE
Error:(252, 5) error: duplicate value for resource 'attr/helperTextColor' with config ''.

### ISSUE THREAD

**Issue by kibarmusti** [HITGIF/TextFieldBoxes#46]
C:\Users\qwe\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\7cf6837638c36c9f6ecfbeb693286dca\res\values\values.xml
Error:(252, 5) error: duplicate value for resource 'attr/helperTextColor' with config ''.
Error:(252, 5) error: resource previously defined here.

AGPBI: {"kind":"error","text":"error: duplicate value for resource \u0027attr/helperTextColor\u0027 with config \u0027\u0027.","sources":[{"file":"C:\\Users\\qwe\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-27.0.2.aar\\7cf6837638c36c9f6ecfbeb693286dca\\res\\values\\values.xml","position":{"startLine":251,"startColumn":4,"startOffset":27028,"endColumn":68,"endOffset":27092}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource previously defined here.","sources":[{"file":"C:\\Users\\qwe\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-27.0.2.aar\\7cf6837638c36c9f6ecfbeb693286dca\\res\\values\\values.xml","position":{"startLine":251,"startColumn":4,"startOffset":27028,"endColumn":68,"endOffset":27092}}],"original":"","tool":"AAPT"}

**Comment by HITGIF** [comment]
Which version are you compiling?
