### ISSUE TITLE
Compact?

### ISSUE THREAD

**Issue by KennyGoers** [HITGIF/TextFieldBoxes#48]
Any thoughts on supporting the compact Text Fields? How difficult would it be? I think support for these is coming in the design library but it seems to be moving very slowly.

Thanks

**Comment by HITGIF** [comment]
What do you mean by supporting the compact? Currently the field already extends the AppCompactAutoCompleteTextView.

**Comment by KennyGoers** [comment]
Sorry I missed your response.

What I was referring to was the Material Design guidelines added a version of the text box that had a shorter overall height for the case where there were a lot of fields on a form.   Was wondering if this might be supported, there is initial support for it in the stand alone design library, but that isn't buildable for the most part.

**Comment by HITGIF** [comment]
So you mean the `Dense Layout`.
That'll be a great idea and I think I'll probably add support to it in the next release :)

**Comment by HITGIF** [comment]
Added in 1.4.0
