### ISSUE TITLE
Issues with layout

### ISSUE THREAD

**Issue by mario** [HITGIF/TextFieldBoxes#49]
<studio.carbonylgroup.textfieldboxes.TextFieldBoxes
        android:id="@+id/text_field_boxes"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/image_logo"
        android:layout_marginEnd="@dimen/activity_horizontal_margin"
        android:layout_marginStart="@dimen/activity_horizontal_margin"
        app:errorColor="@color/nc_white_color_complete"
        app:helperText=" "
        app:labelText="@string/nc_server_url"
        app:panelBackgroundColor="@color/colorPrimary"
        app:primaryColor="@color/nc_white_color_complete">

        <studio.carbonylgroup.textfieldboxes.ExtendedEditText
            android:id="@+id/extended_edit_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:imeOptions="actionDone"
            android:inputType="textUri"
            android:minWidth="5dp"
            android:singleLine="true"
            android:textColor="@color/nc_white_color_complete"/>

    </studio.carbonylgroup.textfieldboxes.TextFieldBoxes>

![screen shot 2018-01-25 at 15 29 36](https://user-images.githubusercontent.com/5810/35393274-cc4d2fa0-01e4-11e8-93b7-307b8191e2b1.png)
![screen shot 2018-01-25 at 15 30 02](https://user-images.githubusercontent.com/5810/35393275-cc686d10-01e4-11e8-81ff-ec388e741cc3.png)

One is Android 6. One is Android 7. Notice how on 6 the TextFieldBoxes takes entire height despite being set to wrap_content :-/

**Comment by HITGIF** [comment]
Fixed in **release 1.3.9** :)

**Comment by mario** [comment]
Awesome, thanks :D

**Comment by mario** [comment]
Sorry, same issue exists still :(

![screen shot 2018-02-08 at 13 38 38](https://user-images.githubusercontent.com/5810/35973380-86f57ccc-0cd5-11e8-9ab6-093994249c82.png)

**Comment by HITGIF** [comment]
Can you provide the entire layout file to reproduce this?

[This](https://gist.github.com/HITGIF/7212d19d15230b1834ef4fb54f8eb138#file-layout-xml) is the layout file I'm testing which is based on yours with unnecessary lines (colors etc.) removed.
And it behaves normally on Android 6.0 (API 23):
![screenshot_1518146718](https://user-images.githubusercontent.com/16971971/36011051-b206e1b6-0d8f-11e8-8554-06b7b94cc803.png)

**Comment by mario** [comment]
<?xml version="1.0" encoding="utf-8"?>


<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@color/colorPrimary"
                android:fitsSystemWindows="true">

    <ImageView
        android:id="@+id/image_logo"
        android:layout_width="96dp"
        android:layout_height="96dp"
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="36dp"
        android:layout_marginTop="92dp"
        android:scaleType="fitXY"
        app:srcCompat="@drawable/ic_logo"/>

    <studio.carbonylgroup.textfieldboxes.TextFieldBoxes
        android:id="@+id/text_field_boxes"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/image_logo"
        android:layout_marginEnd="@dimen/activity_horizontal_margin"
        android:layout_marginStart="@dimen/activity_horizontal_margin"
        app:errorColor="@color/nc_white_color_complete"
        app:helperText=" "
        app:labelText="@string/nc_server_url"
        app:panelBackgroundColor="@color/colorPrimary"
        app:primaryColor="@color/nc_white_color_complete">

        <studio.carbonylgroup.textfieldboxes.ExtendedEditText
            android:id="@+id/extended_edit_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:imeOptions="actionDone"
            android:inputType="textUri"
            android:minWidth="5dp"
            android:singleLine="true"
            android:textColor="@color/nc_white_color_complete"/>

    </studio.carbonylgroup.textfieldboxes.TextFieldBoxes>

    <ProgressBar
        android:id="@+id/progress_bar"
        android:layout_width="@dimen/small_item_height"
        android:layout_height="@dimen/small_item_height"
        android:layout_below="@id/text_field_boxes"
        android:layout_centerHorizontal="true"
        android:layout_marginEnd="@dimen/activity_horizontal_margin"
        android:layout_marginStart="@dimen/activity_horizontal_margin"
        android:layout_marginTop="24dp"
        android:indeterminate="true"
        android:indeterminateTint="@color/nc_white_color_complete"
        android:indeterminateTintMode="src_in"
        android:keepScreenOn="true"
        android:visibility="invisible"/>

    <TextView
        android:id="@+id/helper_text_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/progress_bar"
        android:layout_centerHorizontal="true"
        android:layout_marginEnd="@dimen/activity_horizontal_margin"
        android:layout_marginStart="@dimen/activity_horizontal_margin"
        android:layout_marginTop="56dp"
        android:lines="2"
        android:text="@string/nc_get_from_provider"
        android:textAlignment="center"
        android:textAllCaps="true"
        android:textColor="@color/nc_light_blue_color"/>

</RelativeLayout>

**Comment by HITGIF** [comment]
Sorry that I didn't check on time, but it seems that the link is no longer available.

**Comment by mario** [comment]
<?xml version="1.0" encoding="utf-8"?>


<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/nc_white_color">

    <studio.carbonylgroup.textfieldboxes.TextFieldBoxes
        android:id="@+id/text_field_boxes"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginEnd="@dimen/activity_horizontal_margin"
        android:layout_marginStart="@dimen/activity_horizontal_margin"
        app:errorColor="@color/nc_darkRed"
        app:helperText=" "
        app:panelBackgroundColor="@color/nc_white_color"
        app:primaryColor="@color/colorPrimary">

        <studio.carbonylgroup.textfieldboxes.ExtendedEditText
            android:id="@+id/extended_edit_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:imeOptions="actionDone"
            android:inputType="textUri"
            android:minWidth="5dp"
            android:singleLine="true"
            android:textColor="@color/colorPrimary"/>

    </studio.carbonylgroup.textfieldboxes.TextFieldBoxes>

    <Button
        android:id="@+id/ok_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentEnd="true"
        android:layout_below="@id/text_field_boxes"
        android:layout_marginBottom="12dp"
        android:layout_marginEnd="8dp"
        android:layout_marginTop="8dp"
        android:alpha="0.7"
        android:background="#0000"
        android:enabled="false"
        android:text="@string/nc_proceed"
        android:textColor="@color/colorPrimary"/>

</RelativeLayout>

**Comment by HITGIF** [comment]
Absolutely fixed in 1.4.1 :-)

**Comment by mario** [comment]
Are you sure this time? xD

**Comment by mario** [comment]
Tested, works - amazing work @HITGIF :p
