### ISSUE TITLE
Are you open for suggestions?

### ISSUE THREAD

**Issue by Rainer-Lang** [HITGIF/TextFieldBoxes#5]
I'm using a very good lib for EditText with label - but it's not maintained anymore.
So I'm searching for a replacement.

**Comment by HITGIF** [comment]
Of course, any suggestions are welcome :)

**Comment by Rainer-Lang** [comment]
@HITGIF Perfect. Thanks.
Right now I'm using https://github.com/rengwuxian/MaterialEditText - and it's still really great. But it's not maintained anymore - and there are bugs and features missing.

- What I need is an icon in front (left) of the EditText. https://github.com/rengwuxian/MaterialEditText/raw/master/images/material_design_icon.png
- An "delete" icon on the right if there is text inside the EditText.
- Label "not floating", always visible - so I could use label AND hint text at the same time.
- Is it possible to define min text length? -> FOUND IT: app:minCharacters="5"
- Possible to have a look more like the default EditText?

**Comment by HITGIF** [comment]
Thanks for the suggestions first.
- the icon is now avaiable in the 1.1.0 release, you can use `app:iconSignifier` in xml, see README for more detail.
- delete button is now listed in TODO, and will hopefully be coming soon XD
- I guess the Placeholder, or the actual "hint" is what you're asking for, and I admit that my way of naming the floating label as "hint" is improper.
For now you can use `getEditText().setHint()` in Java code to achieve that, yet I'm certainly going to add it as an attribute to make life easier and the proper name for floating label will be change back :)
- you got it XD
- You're hoping for a UI that looks like the original EditText? Does it mean to cut off the box or what? Could you explain it a little more?

**Comment by Rainer-Lang** [comment]
Very impressive!

For the EditText look: https://material.io/guidelines/components/text-fields.html#text-fields-layout
-> [image](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xObG9aeVV6bWlkX2c/cursor.png)

**Comment by HITGIF** [comment]
Well, what I'm doing is actually something else in the guideline called [Text Field Boxes](https://material.io/guidelines/components/text-fields.html#text-field-boxes), not a extented EditText. [Image here](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOM2thSDFxNXdWWlU/discoverable_states.png)

This is distinct from the original EditText :)

**Comment by Rainer-Lang** [comment]
Ah I see :-)
Thanks.
