### ISSUE TITLE
Will not compile after including the library

### ISSUE THREAD

**Issue by gogoalsoft** [HITGIF/TextFieldBoxes#50]
After including the library in Android Studio 2.3, targeting SDK 25 by: 

allprojects {
    repositories {
      ...
      maven { url 'https://jitpack.io' }
    }
}
dependencies {
    compile 'com.github.HITGIF:TextFieldBoxes:1.3.8'
}

 

I got the following error:

Error:(754) Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?

which references a string resource: 

<string name="counter_label_text_constructor">%s%s%s%s</string>

I THINK the correct way to do this, is either to set formated=false for this string, or specify in the way: %1$s%2$s%3$s%4$s.

**Comment by gogoalsoft** [comment]
Actually, if I include version 1.3.7, the error will go away, but since I am using SDK 25, there are some v26 errors. Does the library require linking to v26? What can I do?

**Comment by HITGIF** [comment]
Should be fixed now, try`compile 'com.github.HITGIF:TextFieldBoxes:3c9a1115f0'`.
What specifically are the v26 errors? Are they affecting the compiling and usage?

**Comment by gogoalsoft** [comment]
I think the v26 errors come from the gradle file referencing v27 support and design libraries.
Some static resources must have been included in those and when I'm using sdk 25 those resources are missing. App will not compile as the R file cannot be created.

How do I include them?

**Comment by HITGIF** [comment]
What's your `compileSdkVersion`?
If it's below 27, upgrading it to 27 solves the issue.

**Comment by HITGIF** [comment]
The string resource compiling issue is now fixed in **release 1.3.9**.
