### ISSUE TITLE
Bottom Line should be 1dp without focus

### ISSUE THREAD

**Issue by KennyGoers** [HITGIF/TextFieldBoxes#53]
In the Material Design Spec it calls for The Bottom Line to be 1dp without focus and 2dp with focus, currently it is always 2dp.

**Comment by HITGIF** [comment]
This rule is only for the stand-alone text field.

While for the text field boxes the bottom line is always 2dp in all states as required under [here](https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes).
![image](https://user-images.githubusercontent.com/16971971/36526624-48a24164-17af-11e8-9c89-7bd2dd59fc5d.png)
