### ISSUE TITLE
Adding a TextWatcher on ExtendedEditText causes infinite Loop crash with setError

### ISSUE THREAD

**Issue by akalinxy** [HITGIF/TextFieldBoxes#59]
I attached a textWatcher onto the ExtendedEditText, and whenever the text is empty, it calls setError()

but calling setError causes the TextWatcher to be triggered and since the text is empty ic calls setError()

but that triggers the TextWatcher again and since its still empty it calls setError()

but the TextWatcher is triggered again. I cannot have a reactive layout like that, is this intentional?

**Comment by HITGIF** [comment]
fixed in d2ca9af2cb2fd8e20a0133f5fd88a847f43f699d :)
This was caused by a method of making the cursor blink when gaining focus, which involves a previous mechanism of changing the text and then making it empty.

**Comment by HITGIF** [comment]
You can now use 1.4.2 without this issue.
