### ISSUE TITLE
Error:(160, 42) No resource found that matches the given name (at 'layout_toLeftOf' with value '@id/text_field_boxes_counter').

### ISSUE THREAD

**Issue by marcespinoza** [HITGIF/TextFieldBoxes#61]
I have this problem id, the @+id/text_field_boxes_counter is defined after

`<android.support.v7.widget.AppCompatTextView
                android:id="@+id/text_field_boxes_helper"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true"
                android:layout_marginEnd="@dimen/helper_marginEnd"
                android:layout_marginRight="@dimen/helper_marginEnd"
                android:layout_toLeftOf="@id/text_field_boxes_counter"
                android:layout_toStartOf="@id/text_field_boxes_counter"
                android:textSize="@dimen/helper_text_size" />
            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/text_field_boxes_counter"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
                android:textSize="@dimen/counter_text_size" />`

**Comment by HITGIF** [comment]
fixed in 1.4.2 :)
