### ISSUE TITLE
Custom ripple color

### ISSUE THREAD

**Issue by ako2345** [HITGIF/TextFieldBoxes#67]
I didn't find an opportunity to customize ripple color of the view. It would be great to add this feature.

**Comment by ako2345** [comment]
I found the way to do that:
```
    <style name="TextFieldBoxes">
        <item name="android:colorControlHighlight">@color/colorRippleEffectLight</item>
    </style>
```
After that you should set this as TextFieldBoxes theme.
Can you add this to the docs?

**Comment by HITGIF** [comment]
Added :)
