### ISSUE TITLE
Whether to consider adding a delete key?

### ISSUE THREAD

**Issue by mozhijie** [HITGIF/TextFieldBoxes#7]
Great, Thank you! Whether to consider adding a delete key?

**Comment by HITGIF** [comment]
yep right, I'll put it in todo! Thanks :)

**Comment by mozhijie** [comment]
I'm looking forward to! Thank you :)

**Comment by HITGIF** [comment]
Delete key is now available in release 1.2.0 🎉🎉🎉
Check out README for more detail :)

**Comment by mozhijie** [comment]
Great 👍👍👍
Thank you!
