### ISSUE TITLE
No actions on long click?

### ISSUE THREAD

**Issue by mario** [HITGIF/TextFieldBoxes#76]
Does ExtendedEditText supports the usual copy, paste and other actions when long clicking? Because absolutely nothing comes up when I long click on an empty ExtendedEditText

**Comment by mario** [comment]
Seems to be  generic issue with edittext when it's empty.

**Comment by HITGIF** [comment]
Works fine for me.
Make sure there's something in your clipboard.

**Comment by mario** [comment]
@HITGIF of course there's something on the clipboard :) Number of people reported this too so it's not only me.

The issue is when ExtendedEditText is empty. Can you check tht? :)

**Comment by ivwitxsc** [comment]
> @HITGIF of course there's something on the clipboard :) Number of people reported this too so it's not only me.
> 
> The issue is when ExtendedEditText is empty. Can you check tht? :)

did you solve the proble？
