### ISSUE TITLE
Version Mixes For v27.1.1 And v27.0.1 In The Library(May Lead To Crashes)

### ISSUE THREAD

**Issue by naseemali925** [HITGIF/TextFieldBoxes#77]
I Am Getting An Error In The Apps build.gradle File When I Sync It. Says Versions Mixes Found For Both v27.1.1 And v27.0.1
![err](https://user-images.githubusercontent.com/6770106/39400493-f4adbbf0-4b4e-11e8-8c71-486b3f5f78ad.PNG)
![error](https://user-images.githubusercontent.com/6770106/39400494-f4f185c4-4b4e-11e8-858d-0222dbbdd6fc.PNG)

**Comment by The28AWG** [comment]
Use exclude:
```
implementation ('com.github.HITGIF:TextFieldBoxes:1.4.3'){
        exclude group: 'com.android.support', module: 'appcompat-v7'
}
```

**Comment by eyildiz** [comment]
Sorry, but it's not fixing. @The28AWG . Am i missing something ?

**Comment by The28AWG** [comment]
This project used appcompat-v7 and design library.
https://github.com/HITGIF/TextFieldBoxes/blob/ac2a6ec244e2d77e34421c3d23e54936ae747893/textfieldboxes/build.gradle#L27
Use:
```
implementation ('com.github.HITGIF:TextFieldBoxes:1.4.3'){
        exclude group: 'com.android.support'
}
```
Or no idea. Clean and rebuild project after changes.
