### ISSUE TITLE
Don't create new objects in onDraw method

### ISSUE THREAD

**Issue by SimonMarquis** [HITGIF/TextFieldBoxes#8]
It's a best practice not to create new object in the critical path (onDraw is called a lot of time).

https://github.com/HITGIF/TextFieldBoxes/blob/3273849f1f1eb238a26f696613b791d118ec1c5b/textfieldboxes/src/main/java/studio/carbonylgroup/textfieldboxes/ClipToBoundsView.java#L37-L44

`clipPath`, `cornerRadius`, `RectF` could be initialized in onCreate method, and `getClipBounds` requested only when the view size changes.

**Comment by abc612008** [comment]
Thanks for your suggestion. Already fixed in 7d3f09a55d51dac212a29cd4c72e60f493638952.
