### ISSUE TITLE
CounterTextColor conflicting with material component library

### ISSUE THREAD

**Issue by dineshmm23** [HITGIF/TextFieldBoxes#97]
`C:\Users\dunzo\.gradle\caches\transforms-1\files-1.1\material-1.1.0-alpha03.aar\1ab18e7ee101c339c8c292d14ea1a75e\res\values\values.xml:1094:5-1109:23: AAPT: error: duplicate value for resource 'attr/counterTextColor' with config ''.`

In conflict with these libraries-->  

> implementation 'com.google.android.material:material:1.1.0-alpha03'

After migrating to `Androidx`, I am getting merged resource conflicts with your library 

>  To Avoid, can it be renamed (if possible in the next release)

**Comment by taar1** [comment]
I have the same issue:
`error: duplicate value for resource 'attr/counterTextColor' with config ''.`

 I have to downgrade your library to version 1.3.3 to get it to work.
Or I have to downgrade material library to com.google.android.material:material:1.1.0-alpha01

But both can't be the solution. As soon as material:1.1.0 will be released the problem will reoccur.

We need an updated library with other variable names to avoid that conflict. 
Thanks.

**Comment by HITGIF** [comment]
fixed in 1.4.5
